deploy:
	helm upgrade --install infrastructure . --namespace=infrastructure --create-namespace

debug:
	helm upgrade --install infrastructure . --dry-run --debug --namespace=infrastructure --create-namespace