grafana:
  service:
    type: LoadBalancer
  persistence:
    enabled: true

prometheus-adapter:
  prometheus:
    url: http://infrastructure-prometheus-server
    port: 80
  rules:
    default: false
    custom:
      - seriesQuery: 'travelaudience_prime_calculator_operations_ops{kubernetes_namespace!="",kubernetes_pod_name!=""}'
        resources:
          overrides:
            kubernetes_namespace: {resource: "namespace"}
            kubernetes_pod_name: {resource: "pod"}
        name:
          matches: ""
          as: "ops"
        metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)'